# code quaality check using check style (it is already configured in maven file)
# SAST 
name: code quality check using Checkstyle linter
on:
    workflow_call:
jobs:
    code-quality-check:
        runs-on: ubuntu-latest
        steps:
            - name: code checkout
              uses: actions/checkout@v4

            - name: setup java
              uses: actions/setup-java@v4
              with:
                distribution: "temurin"
                java-version: "21"
                cache: "maven"
# use ./mvnw verify as checkstyle is already configure in maven
            - name: run checkstyle
              run: ./mvnw verify

# run semgrep for SAST(static application security testing) and 
            - name: run semgrep for SAST
              uses: semgrep/semgrep-action@v1
              with:
                config: >-
                  p/java
                  p/owasp-top-10
