name: code quality check using Checkstyle linter
on:
    workflow_call:
jobs:
    code-quality-check:
        runs-on: ubuntu-latest
        steps:
            - name: code checkout
              uses: actions/checkout@v4

            - name: setup java
              uses: actions/setup-java@v4
              with:
                distribution: "temurin"
                java-version: "21"
                cache: "maven"

            - name: run checkstyle
              run: ./mvnw verify
