name: Dependency and CVEs check
on:
    workflow_call:
jobs:
    Dependency-check:
        runs-on: ubuntu-latest
        steps:
            - name: code checkout
              uses: actions/checkout@v4

            - name: setup jdk
              uses: actions/setup-java@v4
              with:
                java-version: "21"
                distribution: "temurin"
                cache: "maven"
# for NVD API key request api key at their website
            - name: Run OWASP Dependency Check
              env:
                NVD_API_KEY: ${{ secrets.NVD_API_KEY }}
              run: |
                mvn clean compile org.owasp:dependency-check-maven:check \
                -DnvdApiKey=$NVD_API_KEY \
                -DfailBuildOnCVSS=7

            - name: upload scan report
              if: always()
              uses: actions/upload-artifact@v4
              with:
                name: dependency-check-report
                path: target/dependency-check-report.html   