name: deploy petclinic app
on:
    workflow_call:
jobs:
    deployment:
        env:
         DOCKERHUB_USER: ${{ secrets.DOCKERHUB_USER}}
         DOCKER_TAG: ${{ github.sha}}
        runs-on: self-hosted
        steps:
            - name: code checkout
              uses: actions/checkout@v4

            - name: setup docker compose
              uses: docker/setup-compose-action@v2

            - name: run petclinic
              run: docker compose down && docker compose up -d