name: devsecops pipeline
on:
    push:
        branches: [main]
jobs:
    code-quality:
        uses: ./.github/workflows/code-quality.yml
    dependency-scan:
        uses: ./.github/workflows/dependency-scan.yml
        secrets: inherit
    dockerfile-scan:
        uses: ./.github/workflows/dockerfile-scan.yml
    secrets-scan:
        uses: ./.github/workflows/secrets-scan.yml
    docker-build-and-push:
        needs: [code-quality,dependency-scan,dockerfile-scan,secrets-scan]
        uses: ./.github/workflows/docker-build-and-push.yml