# Checking  Secrets, passwords, API keys using Gitleaks
name: secret scan using Gitleaks
on:
    workflow_call:
jobs:
    secret-scan:
        runs-on: ubuntu-latest
        steps:
            - name: code checkout
              uses: actions/checkout@v4
              with:
                fetch-depth: 0

            - name: secret scanning using Gitleaks
              uses: gitleaks/gitleaks-action@v2
              with:
                GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}